ccflags-y := -Iinclude/drm
cirrus-y   := cirrus_crtc.o cirrus_encoder.o cirrus_device.o cirrus_display.o \
	cirrus_drv.o cirrus_fbdev.o cirrus_framebuffer.o \
	cirrus_kms.o cirrus_vga.o

obj-$(CONFIG_DRM_KVM_CIRRUS) += cirrus.o
