/*!****************************************************************************
@File           sgx_ukernel_status_codes.h

@Title          SGX microkernel debug status codes

@Author         Imagination Technologies

@Date           7th Feb 2008

@Copyright      Copyright 2003-2008 by Imagination Technologies Limited.
                All rights reserved. No part of this software, either material
                or conceptual may be copied or distributed, transmitted,
                transcribed, stored in a retrieval system or translated into
                any human or computer language in any form by any means,
                electronic, mechanical, manual or otherwise, or disclosed to
                third parties without the express written permission of
                Imagination Technologies Limited, Home Park Estate,
                Kings Langley, Hertfordshire, WD4 8LZ, U.K.

@Platform       Generic

@Description    SGX microkernel debug status codes

@DoxygenVer

******************************************************************************/

/******************************************************************************
Modifications :-
$Log: sgx_ukernel_status_codes.h $

 --- Revision Logs Removed --- 
*****************************************************************************/

#if !defined (__SGX_UKERNEL_STATUS_CODES_H__)
#define __SGX_UKERNEL_STATUS_CODES_H__

/*
	It would be nice to put these definitions into an enumeration, but USEASM
	only has access to the C preprocessor so macros are required.
*/

/*
	Bits 24-31 of these codes (0xAD) are a magic number used to help
	distinguish between them and other debug information which can be
	optionally dumped into the status buffer, e.g. sync object values.
*/

/*
	Microkernel trace codes
*/
#define MKTC_EHEVENT_3DMEMFREE					0xAD000001
#define MKTC_EHEVENT_PIXELENDRENDER				0xAD000002
#define MKTC_EHEVENT_ISPBREAKPOINT				0xAD000004
#define MKTC_EHEVENT_TAFINISHED					0xAD000005
#define MKTC_EHEVENT_MEMTHRESHOLD				0xAD000006
#define MKTC_EHEVENT_OUTOFMEM					0xAD000007
#define MKTC_EHEVENT_TATERMINATE				0xAD000008
#define MKTC_EHEVENT_TIMER					0xAD000009
#define MKTC_EHEVENT_SWEVENT					0xAD00000A
#define MKTC_EHEVENT_2DCOMPLETE					0xAD00000B
#define MKTC_EHEVENT_MTE_DRAIN_COMPLETE				0xAD00000C

#define MKTC_3DEVENT_3DMEMFREE					0xAD000100
#define MKTC_3DEVENT_PIXELENDRENDER				0xAD000101
#define MKTC_3DEVENT_ISPBREAKPOINT				0xAD000102
#define MKTC_3DEVENT_END					0xAD000104
#define MKTC_3DLB_3DMEMFREE					0xAD000180
#define MKTC_3DLB_PIXELENDRENDER				0xAD000181
#define MKTC_3DLB_ISPBREAKPOINT					0xAD000182
#define MKTC_3DLB_FIND3D					0xAD000183
#define MKTC_3DLB_END						0xAD000184

#define MKTC_TAEVENT_TAFINISHED					0xAD000200
#define MKTC_TAEVENT_END					0xAD000202
#define MKTC_TALB_TAFINISHED					0xAD000280
#define MKTC_TALB_FINDTA					0xAD000281
#define MKTC_TALB_END						0xAD000282

#define MKTC_CRRL_WRITEOPSBLOCKED				0xAD000300
#define MKTC_CRRL_READOPSBLOCKED				0xAD000301
#define MKTC_CRRL_FOUNDRENDER					0xAD000302
#define MKTC_CRRL_NORENDER					0xAD000303
#define MKTC_CRRL_TARC_DIFFERENT				0xAD000304
#define MKTC_FINDRENDER_BRN_23378				0xAD000308
#define MKTC_CRRL_BLOCKEDRC					0xAD000309
#define MKTC_CRRL_BLOCKEDRTDATA					0xAD00030A
#define MKTC_CRRL_CONTEXT_SUSPENDED				0xAD00030B
#define MKTC_CRRL_TAWAITINGFORMEM				0xAD00030C
#define MKTC_CRRL_TAOOMBUTPRIOINV				0xAD00030D

#define MKTC_KICKRENDER_START					0xAD000400
#define MKTC_KICKRENDER_OVERLAP					0xAD000401
#define MKTC_KICKRENDER_ISP_START				0xAD000402
#define MKTC_KICKRENDER_RESUME					0xAD000403
#define MKTC_KICKRENDER_CONFIG_REGION_HDRS			0xAD000404
#define MKTC_KICKRENDER_END					0xAD000408
#define MKTC_KICKRENDER_RENDERCONTEXT				0xAD000409
#define MKTC_KICKRENDER_RTDATA					0xAD00040A
#define MKTC_KICKRENDER_PID					0xAD00040B

#define MKTC_RENDERFINISHED_START				0xAD000500
#define MKTC_RF_START_NEXT_MT					0xAD000501
#define MKTC_RF_ALL_MTS_DONE					0xAD000502
#define MKTC_RENDERFINISHED_END					0xAD000503
#define MKTC_VISQUERY_START					0xAD000504
#define MKTC_VISQUERY_END					0xAD000505
#define MKTC_TRANSFERRENDERFINISHED_START			0xAD000508
#define MKTC_TRANSFERRENDERFINISHED_END				0xAD000509
#define MKTC_TRF_UPDATESTATUSVALS				0xAD00050A
#define MKTC_TRF_UPDATESTATUSVALS_DONE				0xAD00050B

#define MKTC_PIXELENDRENDER_START				0xAD000600
#define MKTC_PIXELENDRENDER_AFTERLOCK				0xAD000601
#define MKTC_PIXELENDRENDER_END					0xAD000602
#define MKTC_PIXELENDRENDER_TLQEND				0xAD000603

#define MKTC_3DMEMFREE_START					0xAD000700
#define MKTC_3DMEMFREE_AFTERLOCK				0xAD000701
#define MKTC_3DMEMFREE_TESTEOR					0xAD000702
#define MKTC_3DMEMFREE_END					0xAD000703

#define MKTC_KICKTA_START					0xAD000800
#define MKTC_KICKTA_OVERLAP					0xAD000801
#define MKTC_KICKTA_RESETCONTEXT				0xAD000802
#define MKTC_KICKTA_VDM_START					0xAD000803
#define MKTC_KICKTA_END						0xAD000804
#define MKTC_KICKTA_RENDERCONTEXT				0xAD000805
#define MKTC_KICKTA_RTDATA					0xAD000806
#define MKTC_KICKTA_RESET_VDMCSSTATUS				0xAD000807
#define MKTC_KICKTA_RESET_BUFFERS				0xAD000808
#define MKTC_KICKTA_PID						0xAD000809
#define MKTC_KICKTA_TACMD_DEBUG					0xAD00080A
#define MKTC_KICKTA_FREECONTEXT					0xAD00080B
#define MKTC_KICKTA_PIM_PATCHING				0xAD00080C

#define MKTC_KICKTA_CHKPT_START_DUMMY_CS			0xAD0008A1
#define MKTC_KICKTA_CHKPT_START_DUMMY_TAK			0xAD0008A2
#define MKTC_KICKTA_CHKPT_WAIT_FOR_DUMMY_KICK			0xAD0008A3
#define MKTC_KICKTA_CHKPT_WAIT_NEXT_CORE			0xAD0008A4
#define MKTC_KICKTA_CHKPT_RESET_COMPLETE			0xAD0008A5
#define MKTC_KICKTA_CHKPT_CHECK_SWITCH				0xAD0008A6

#define MKTC_HOSTKICK_START					0xAD000900
#define MKTC_HOSTKICK_END					0xAD000901
#define MKTC_HOSTKICK_PROCESS_QUEUES_END			0xAD000902
#define MKTC_HOSTKICK_2D					0xAD000903
#define MKTC_HOSTKICK_TRANSFER					0xAD000904
#define MKTC_HOSTKICK_TA					0xAD000905
#define MKTC_HOSTKICK_PROCESS_QUEUES				0xAD000906
#define MKTC_HOSTKICK_RESUME					0xAD000908
#define MKTC_HOSTKICK_POWEROFF					0xAD000909
#define MKTC_HOSTKICK_IDLE					0xAD00090A
#define MKTC_HOSTKICK_CTXSUSPEND				0xAD00090B
#define MKTC_HOSTKICK_CTXRESUME					0xAD00090C

#define MKTC_TIMER_POTENTIAL_TA_LOCKUP				0xAD000A00
#define MKTC_TIMER_POTENTIAL_3D_LOCKUP				0xAD000A01
#define MKTC_TIMER_CTAL_START					0xAD000A02
#define MKTC_TIMER_CTAL_END					0xAD000A03
#define MKTC_TIMER_C3DL_START					0xAD000A04
#define MKTC_TIMER_C3DL_END					0xAD000A05
#define MKTC_TIMER_LOCKUP					0xAD000A0A
#define MKTC_TIMER_NOT_TA_LOCKUP				0xAD000A0B
#define MKTC_TIMER_NOT_3D_LOCKUP				0xAD000A0C
#define MKTC_TIMER_2D_LOCKUP					0xAD000A0D
#define MKTC_TIMER_POTENTIAL_2D_LOCKUP				0xAD000A10
#define MKTC_TIMER_C2DL_START					0xAD000A11
#define MKTC_TIMER_C2DL_END					0xAD000A12
#define MKTC_TIMER_NOT_2D_LOCKUP				0xAD000A13
#define MKTC_TIMER_ABORTALL					0xAD000A0E
#define MKTC_TIMER_END						0xAD000A0F

#define MKTC_HWR_START						0xAD000B00
#define MKTC_HWR_END						0xAD000B01
#define MKTC_HWR_HKS						0xAD000B02
#define MKTC_HWR_PRL						0xAD000B03
#define MKTC_HWR_PRL_DP						0xAD000B04
#define MKTC_HWR_CRL						0xAD000B05
#define MKTC_HWR_CRL_DP						0xAD000B06
#define MKTC_HWR_TRL						0xAD000B07
#define MKTC_HWR_TRL_DP						0xAD000B08
#define MKTC_HWR_ISC						0xAD000B09
#define MKTC_HWR_2DL						0xAD000B0A

#define MKTC_URSV_START						0xAD000C00
#define MKTC_URSV_UPDATEWRITEOPS				0xAD000C01
#define MKTC_URSV_UPDATESTATUSVALS				0xAD000C03
#define MKTC_URSV_UPDATESTATUSVALS_DONE				0xAD000C04
#define MKTC_URSV_END						0xAD000C05

#define MKTC_STORETACONTEXT_START				0xAD000D00
#define MKTC_STORETACONTEXT_END					0xAD000D01
#define MKTC_LOADTACONTEXT_START				0xAD000D02
#define MKTC_LOADTACONTEXT_END					0xAD000D03
#define MKTC_STORE3DCONTEXT_START				0xAD000D04
#define MKTC_STORE3DCONTEXT_END					0xAD000D05
#define MKTC_LOAD3DCONTEXT_START				0xAD000D06
#define MKTC_LOAD3DCONTEXT_END					0xAD000D07

#define MKTC_FINDTA_POWERREQUEST				0xAD000E00
#define MKTC_FINDTA_TA3D_OVERLAP_BLOCKED			0xAD000E01
#define MKTC_FINDTA_RTDATA_RENDERING				0xAD000E02
#define MKTC_FINDTA_3DRC_DIFFERENT				0xAD000E03
#define MKTC_FINDTA_WRITEOPSBLOCKED				0xAD000E04
#define MKTC_FINDTA_READOPSBLOCKED				0xAD000E05
#define MKTC_FINDTA_RESIZE_PB					0xAD000E06
#define MKTC_FINDTA_RESIZE_PB_BLOCKED				0xAD000E07
#define MKTC_FINDTA_SHRINK_PB					0xAD000E08
#define	MKTC_FINDTA_TAPB_DIFFERENT				0xAD000E09
#define	MKTC_FINDTA_TACONTEXT_DIFFERENT				0xAD000E0A
#define MKTC_FINDTA_TA2D_OVERLAP_BLOCKED			0xAD000E0B
#define MKTC_FINDTA_CONTEXT_SUSPENDED				0xAD000E0C
#define MKTC_FINDTA_SRC_READOPSBLOCKED				0xAD000E0D
#define MKTC_FINDTA_SRC_WRITEOPSBLOCKED				0xAD000E0E

#define MKTC_CTRL_SRCREADOPSBLOCKED				0xAD000F00
#define MKTC_CTRL_SRCWRITEOPSBLOCKED				0xAD000F01
#define MKTC_CTRL_DSTREADOPSBLOCKED				0xAD000F02
#define MKTC_CTRL_DSTWRITEOPSBLOCKED				0xAD000F03
#define MKTC_CTRL_TARC_DIFFERENT				0xAD000F04
#define MKTC_CTRL_CONTEXT_SUSPENDED				0xAD000F05

#define MKTC_DPTA_START						0xAD001000
#define MKTC_DPTA_UPDATESTATUSVALS				0xAD001001
#define MKTC_DPTA_UPDATESTATUSVALS_DONE				0xAD001002
#define MKTC_DPTA_NORENDER					0xAD001003
#define MKTC_DPTA_MEMFREE					0xAD001004
#define MKTC_DPTA_INC_COMPLETECOUNT				0xAD001005

#define MKTC_INVALDC 						0xAD001100
#define MKTC_INVALPT 						0xAD001101
#define MKTC_INVALSLC						0xAD001102
#define MKTC_INVALDATA						0xAD001103

#define MKTC_RESTARTTA						0xAD001200
#define MKTC_CSABORTNONGBL					0xAD001201
#define MKTC_CSABORTALL						0xAD001202
#define MKTC_CSRENDERINPROGRESS					0xAD001203
#define MKTC_TATERMRENDERINPROGRESS				0xAD001204
#define MKTC_RESTARTTANORENDER					0xAD001205
#define MKTC_SPM_KICKRENDER					0xAD001206
#define MKTC_SPM_RESUME_ABORTCOMPLETE				0xAD001208
#define	MKTC_RESUMEVDM						0xAD001209
#define	MKTC_REMOVE_RESERVE_MEM					0xAD00120A
#define	MKTC_INCREASEZLSTHRESHOLD				0xAD00120B
#define MKTC_CSFORCEABORTALL					0xAD00120C

#define MKTC_DUMMY_DEPTH					0xAD00120D
#define MKTC_DUMMY_DEPTH_CS					0xAD00120E

#define MKTC_MTETE_OOM						0xAD00120F
#define	MKTC_MTETE_OOM_FIRST_STORE_REF				0xAD001210
#define MKTC_MERGE_STATE_TABLES					0xAD001211
#define MKTC_NO_PAGES_LEFT_FOR_23055				0xAD001212
#define MKTC_NO_STATE_MODS					0xAD001213
#define MKTC_FIND_MTE_PAGE_IN_STATE				0xAD001214
#define MKTC_MTE_PAGE_FOUND					0xAD001215
#define MKTC_MOVE_MTE_PAGE_TO_TA_STATE				0xAD001216
#define MKTC_MOVE_MTE_PAGE_TO_TA_STATE_END			0xAD001217
#define MKTC_ZERO_ZLS_THRESHOLD					0xAD001218
#define MKTC_RESTORE_ZLS_THRESHOLD				0xAD001219
#define MKTC_FIND_MTE_PAGE_IN_CSM				0xAD00121A
#define MKTC_REISSUE_MTE_PAGE					0xAD00121B
#define MKTC_REISSUE_MTE_PAGE_REQUIRED				0xAD00121C
#define MKTC_REISSUE_MTE_PAGE_END				0xAD00121D
#define MKTC_RESET_TE_PSG					0xAD00121E

#define MKTC_OOM_WRITEOPSBLOCKED				0xAD00121F
#define MKTC_OOM_READOPSBLOCKED					0xAD001220
#define MKTC_OOM_SRC_WRITEOPSBLOCKED				0xAD001221
#define MKTC_OOM_SRC_READOPSBLOCKED				0xAD001222
#define MKTC_OOM_SPM_DEADLOCK					0xAD001223
#define MKTC_OOM_SPM_DEADLOCK_MEM_ADDED				0xAD001224
#define MKTC_BRN27311_RESET					0xAD001225
#define	MKTC_SPM_INVALID_ZLSCONFIG				0xAD001226

#define MKTC_SPM_ALREADY_DRAINED				0xAD001227
#define MKTC_DRAIN_COMPLETE					0xAD001228
#define MKTC_DRAIN_SET_FLAG					0xAD001229

#define MKTC_OOM_TYPE_MT					0xAD00122A
#define MKTC_OOM_TYPE_GLOBAL					0xAD001230
#define MKTC_OOM_CAUSE_GBL_OOM					0xAD001231

#define MKTC_CHECK_MTE_PAGE_REISSUE				0xAD001240
#define MKTC_CPRI_VALID_ENTRIES					0xAD001241
#define MKTC_CPRI_STORE_DPLIST					0xAD001242
#define MKTC_CPRI_STORE_OTPM_CSM				0xAD001243
#define MKTC_CPRI_ABORT_MT_IDX					0xAD001244
#define MKTC_CPRI_ABORT_CORE_IDX				0xAD001245
#define MKTC_CPRI_CSM_TABLE_DATA				0xAD001246
#define MKTC_CPRI_PIM_DATA					0xAD001247
#define MKTC_CPRI_DO_CIRCULAR_TEST				0xAD001248

#define MKTC_CPRI_WRITE_ENTRIES					0xAD001249

#define	MKTC_MTE_ENTRY_NOT_IN_ANY_LIST				0xAD001250

#define	MKTC_SPMAC_IGNORE_TERMINATE				0xAD001251

#define MKTC_SPMAC_REQUEST_3D_TIMEOUT				0xAD001252
#define MKTC_SPMAC_3D_TIMEOUT_COMPLETE				0xAD001253

/* PB Load/store status */
#define MKTC_LOADTAPB_START					0xAD001300
#define MKTC_LOADTAPB_END					0xAD001301
#define MKTC_STORETAPB_START					0xAD001302
#define MKTC_STORETAPB_END					0xAD001303
#define MKTC_LOAD3DPB_START					0xAD001304
#define MKTC_LOAD3DPB_END					0xAD001305
#define MKTC_STORE3DPB_START					0xAD001306
#define MKTC_STORE3DPB_END					0xAD001307
#define MKTC_LOADTAPB_PAGETABLE_DONE				0xAD001308
#define MKTC_LOAD3DPB_PAGETABLE_DONE				0xAD001309

#define MKTC_TIMER_RC_CLEANUP					0xAD001400
#define MKTC_TIMER_RC_CLEANUP_COMPLETE				0xAD001401
#define MKTC_TIMER_RT_CLEANUP					0xAD001410
#define MKTC_TIMER_RT_CLEANUP_COMPLETE				0xAD001411
#define MKTC_TIMER_RT_CLEANUP_PENDING				0xAD001412
#define MKTC_TIMER_RT_CLEANUP_TIDYPARTIALLIST			0xAD001413
#define MKTC_TIMER_TC_CLEANUP					0xAD001420
#define MKTC_TIMER_TC_CLEANUP_COMPLETE				0xAD001421
#define MKTC_TIMER_2DC_CLEANUP					0xAD001430
#define MKTC_TIMER_2DC_CLEANUP_COMPLETE				0xAD001431
#define MKTC_TIMER_SHAREDPBDESC_CLEANUP				0xAD001440

#define MKTC_TIMER_ISP_SWITCH_POTENTIAL_LOCKUP			0xAD001450
#define MKTC_TIMER_ISP_SWITCH_FORCE_SWITCH			0xAD001451

#define MKTC_UTSO_UPDATEREADOPS					0xAD001600
#define MKTC_UTSO_UPDATEWRITEOPS				0xAD001601

#define MKTC_TAFINISHED_UPDATESTATUSVALS			0xAD001700
#define MKTC_TAFINISHED_UPDATESTATUSVALS_DONE			0xAD001701
#define MKTC_TAFINISHED_NORENDER				0xAD001702
#define MKTC_TAFINISHED_LASTKICK				0xAD001703
#define MKTC_TAFINISHED_FINDRENDER				0xAD001704
#define MKTC_TAFINISHED_FINDTA					0xAD001705
#define MKTC_TAFINISHED_END					0xAD001706
#define MKTC_TAF_SPM_DEADLOCK_MEM_REMOVED			0xAD001707
#define MKTC_TAF_RESERVE_MEM					0xAD001708
#define MKTC_TAF_RESERVE_MEM_REQUEST_RENDER			0xAD001709
#define MKTC_TAF_RESERVE_FREE_RENDER_FINISHED			0xAD00170A
#define MKTC_TAF_RESERVE_FREE_DUMMY_RENDER			0xAD00170B
#define MKTC_TAF_DEBUG_SAS					0xAD00170C
#define MKTC_TAFINISHED_NOCONTEXTSWITCH				0xAD00170D

#define MKTC_TAFINISHED_TERM_COMPLETE_START			0xAD001710
#define MKTC_TAFINISHED_TERM_COMPLETE_END			0xAD001711

#define MKTC_TAFINISHED_ZERO_TAILPTRS				0xAD001720

#define MKTC_2DEVENT_2DCOMPLETE					0xAD001800
#define MKTC_2DEVENT_END					0xAD001801
#define	MKTC_2DLB_2DCOMPLETE					0xAD001802
#define MKTC_2DLB_FIND2D					0xAD001803
#define MKTC_2DLB_END						0xAD001804
#define MKTC_2DCOMPLETE_START					0xAD001805
#define MKTC_2DCOMPLETE_END					0xAD001806
#define MKTC_KICK2D_START					0xAD001807
#define MKTC_KICK2D_END						0xAD001808
#define MKTC_DUMMYPROC2D					0xAD001809
#define MKTC_FTD_SRCREADOPSBLOCKED				0xAD00180A
#define MKTC_FTD_SRCWRITEOPSBLOCKED				0xAD00180B
#define MKTC_FTD_DSTREADOPSBLOCKED				0xAD00180C
#define MKTC_FTD_DSTWRITEOPSBLOCKED				0xAD00180D
#define MKTC_FTD_TA2D_OVERLAP_BLOCKED				0xAD00180E
#define MKTC_U2DSO_UPDATEREADOPS				0xAD00180F
#define MKTC_U2DSO_UPDATEWRITEOPS				0xAD001810
#define MKTC_FTD_TAOPSBLOCKED					0xAD001811
#define MKTC_KICK2D_2DSLAVEPORT					0xAD001812
#define MKTC_KICK2D_2DSLAVEPORT_DONE				0xAD001813
#define MKTC_FTD_CONTEXT_SUSPENDED				0xAD001814
#define MKTC_KICK2D_PID						0xAD001815
#define MKTC_FIND2D_ADDR_SPACE_DIFFERENT			0xAD001816
#define MKTC_FTD_3DOPSBLOCKED					0xAD001817

#define MKTC_FCM_START						0xAD001900
#define MKTC_FCM_END						0xAD001901

#define MKTC_TIMER_ACTIVE_POWER					0xAD001A00
#define MKTC_TIMER_POWER_3D_ACTIVE				0xAD001A01
#define MKTC_TIMER_POWER_TA_ACTIVE				0xAD001A02
#define MKTC_TIMER_POWER_2D_ACTIVE				0xAD001A03
#define MKTC_TIMER_POWER_PENDING_EVENTS				0xAD001A04
#define MKTC_TIMER_POWER_IDLE					0xAD001A05
#define MKTC_TIMER_POWER_OFF					0xAD001A06
#define	MKTC_TIMER_POWER_CCB_ERROR				0xAD001A07
#define	MKTC_TIMER_POWER_RESTART_IMMEDIATE			0xAD001A08

#define MKTC_3DCONTEXT_SWITCH					0xAD001B00
#define MKTC_3DCONTEXT_SWITCH_END				0xAD001B01

#define MKTC_TACONTEXT_SWITCH					0xAD001C00
#define	MKTC_TACONTEXT_SWITCH_FAST				0xAD001C01
#define MKTC_TACONTEXT_SWITCH_END				0xAD001C02

#define MKTC_GETMISCINFO_MEMREAD_START				0xAD001D00
#define MKTC_GETMISCINFO_MEMREAD_END				0xAD001D01
#define MKTC_GETMISCINFO_MEMWRITE_START				0xAD001D02
#define MKTC_GETMISCINFO_MEMWRITE_END				0xAD001D03

#define	MKTC_HALTTA						0xAD001E00
#define MKTC_HTA_SET_FLAG					0xAD001E01
#define MKTC_HTA_SAVE_COMPLEX_PTR				0xAD001E02
#define MKTC_HALTTA_END						0xAD001E03

#define	MKTC_RESUMETA						0xAD001F00
#define	MKTC_RTA_CONTEXT_LOADED					0xAD001F01
#define	MKTC_RTA_MTE_STATE_KICKED				0xAD001F02
#define MKTC_RTA_CMPLX_GEOM_PRESENT				0xAD001F03
#define	MKTC_RTA_CMPLX_STATE_KICKED				0xAD001F04
#define	MKTC_RTA_CHECK_NEXT_SA_PROG				0xAD001F05
#define MKTC_RTA_CORE_COMPLETED					0xAD001F06
#define MKTC_RTA_DEBUG_SAS					0xAD001F07
#define MKTC_RESUMETA_END					0xAD001F0F

#define MKTC_RESUME_SPMCS_START					0xAD001F80
#define MKTC_RSPMCS_OVERLAP					0xAD001F81
#define MKTC_RSPMCS_START_PULSE					0xAD001F82
#define MKTC_RESUME_SPMCS_END					0xAD001F83

#define MKTC_RENDERHALT						0xAD002000
#define MKTC_RH_CLEARFLAGS					0xAD002001
#define MKTC_RH_CTRL_ADDR					0xAD002002
#define MKTC_RH_RGN_ADDR					0xAD002003
#define MKTC_RH_EMPTY_TILE					0xAD002004
#define MKTC_RH_EMPTY_LAST_TILE					0xAD002005
#define MKTC_RH_3D_TIMEOUT					0xAD002006
#define MKTC_RH_NOT_EMPTY					0xAD002007
#define MKTC_RH_OBJECT_COMPLETE					0xAD002008
#define MKTC_RH_STREAM_LINK					0xAD002009
#define MKTC_RH_OBJECT_INCOMPLETE				0xAD00200A
#define MKTC_RH_PRIM_MASK_PRESENT				0xAD00200B
#define MKTC_RH_BYTE_MASK_PRESENT				0xAD00200C
#define MKTC_RH_BYTE_MASK_ZERO					0xAD00200D
#define MKTC_RH_PRIM_MASK_ZERO					0xAD00200E
#define MKTC_RH_INVALIDATE_OBJECTS				0xAD00200F
#define MKTC_RH_OBJECTS_INVALIDATED				0xAD002010
#define MKTC_RH_DPM_RGN_PARSER_IDLE				0xAD002011
#define MKTC_RH_NEXT_RGN_BASE					0xAD002012
#define MKTC_RH_OCC_EXIT					0xAD002013
#define MKTC_RH_STILL_RUNNING					0xAD002020
#define MKTC_RH_CLEARMCI					0xAD002021
#define MKTC_RH_EOR						0xAD002022
#define MKTC_RENDERHALT_END					0xAD002030

#define	MKTC_FIND3D_POWERREQUEST				0xAD002100

#define	MKTC_FIND2D_POWERREQUEST				0xAD002200

#define MKTC_SPM_OOM_POWERREQUEST				0xAD002280
#define MKTC_SPM_AC_POWERREQUEST				0xAD002281
#define MKTC_SPM_RF_POWERREQUEST				0xAD002282

#define	MKTC_UKERNEL_INIT					0xAD002300
#define MKTC_UKERNEL_INIT_DCS_COMPLETE				0xAD002301
#define MKTC_UKERNEL_INIT_VDMKICK_COMPLETE			0xAD002303

#define MKTC_KICKTRANSFERRENDER_START				0xAD002400
#define MKTC_KICKTRANSFERRENDER_ISP_START			0xAD002401
#define MKTC_KICKTRANSFERRENDER_END				0xAD002402
#define MKTC_DUMMYPROCTRANSFER					0xAD002403
#define MKTC_KTR_TQFENCE					0xAD002404
#define MKTC_KICKTRANSFERRENDER_PID				0xAD002405

#define MKTC_HOSTKICK_CLEANUP_RT				0xAD002500
#define MKTC_HOSTKICK_CLEANUP_RC				0xAD002501
#define MKTC_HOSTKICK_CLEANUP_TC				0xAD002502
#define MKTC_HOSTKICK_CLEANUP_2DC				0xAD002503
#define MKTC_HOSTKICK_CLEANUP_PB				0xAD002504
#define MKTC_HOSTKICK_GETMISCINFO				0xAD002505
#define MKTC_HOSTKICK_DATABREAKPOINT				0xAD002506
#define MKTC_HOSTKICK_SETHWPERFSTATUS				0xAD002507

#define MKTC_ZEROPC						0xAD002600

#define MKTC_ASSERT_FAIL					0xAD002700

#define MKTC_SDLB_ILLEGAL					0xAD002800

#define MKTC_SPMEVENT_MEMTHRESHOLD				0xAD002900
#define MKTC_SPMEVENT_OUTOFMEM					0xAD002901
#define MKTC_SPMEVENT_TATERMINATE				0xAD002902
#define MKTC_SPMEVENT_MTE_DRAIN_COMPLETE			0xAD002903
#define MKTC_SPMEVENT_END					0xAD002904
#define MKTC_SPMLB_MEMTHRESHOLD					0xAD002980
#define MKTC_SPMLB_OUTOFMEM					0xAD002981
#define MKTC_SPMLB_TATERMINATE					0xAD002982
#define MKTC_SPMLB_SPMRENDERFINSHED				0xAD002983
#define MKTC_SPMLB_MTE_DRAIN_COMPLETE				0xAD002984
#define MKTC_SPMLB_END						0xAD002985

#define MKTC_SPM_CHECK_MT_DEADLOCK				0xAD002991
#define MKTC_SPM_CHECK_GLOBAL_DEADLOCK				0xAD002992
#define MKTC_SPM_RESERVE_ADDED					0xAD002993

#define MKTC_IBC_ILLEGAL					0xAD002A00

#define MKTC_HWP_CLEARCOUNTERS					0xAD002B00

#define MKTC_TA_FRAMENUM					0xAD002C00
#define MKTC_3D_FRAMENUM					0xAD002C01
#define MKTC_SPM3D_FRAMENUM					0xAD002C02

#define MKTC_HKTA_RENDERCONTEXT					0xAD002D00
#define MKTC_IDLECORE_REFCOUNT_FAIL				0xAD002E00

#define MKTC_MCISTATE_NOT_CLEARED				0xAD002F00


#define MKTC_LOWERED_TO_PDS_THRESHOLD				0xAD003000
#define MKTC_REDUCE_MAX_VTX_PARTITIONS				0xAD003001
#define MKTC_KTAOVERRIDE_MAX_VTX_PARTITIONS			0xAD003002
#define MKTC_KTANOOVERRIDE_MAX_VTX_PARTITIONS			0xAD003003


#define MKTC_IPRB_NORENDERDETAILS				0xAD003010
#define MKTC_IPRB_HAVERENDERDETAILS				0xAD003011

#define MKTC_RENDER_OUT_OF_ORDER				0xAD003020
#define MKTC_RENDER_NOT_OUT_OF_ORDER				0xAD003021

#define MKTC_ZLS_IDLE_BEGIN					0xAD003030
#define MKTC_ZLS_ISP_CLK_GATING_EN				0xAD003031
#define MKTC_ZLS_IDLE_END					0xAD003032

#define MKTSTR(x) #x

struct MKTC {
	IMG_UINT32 m;
	char *s;
} MKTDecoder[] = {

	{ MKTC_EHEVENT_3DMEMFREE, MKTSTR(MKTC_EHEVENT_3DMEMFREE) },
	{ MKTC_EHEVENT_PIXELENDRENDER, MKTSTR(MKTC_EHEVENT_PIXELENDRENDER) },
	{ MKTC_EHEVENT_ISPBREAKPOINT, MKTSTR(MKTC_EHEVENT_ISPBREAKPOINT) },
	{ MKTC_EHEVENT_TAFINISHED, MKTSTR(MKTC_EHEVENT_TAFINISHED) },
	{ MKTC_EHEVENT_MEMTHRESHOLD, MKTSTR(MKTC_EHEVENT_MEMTHRESHOLD) },
	{ MKTC_EHEVENT_OUTOFMEM, MKTSTR(MKTC_EHEVENT_OUTOFMEM) },
	{ MKTC_EHEVENT_TATERMINATE, MKTSTR(MKTC_EHEVENT_TATERMINATE) },
	{ MKTC_EHEVENT_TIMER, MKTSTR(MKTC_EHEVENT_TIMER) },
	{ MKTC_EHEVENT_SWEVENT, MKTSTR(MKTC_EHEVENT_SWEVENT) },
	{ MKTC_EHEVENT_2DCOMPLETE, MKTSTR(MKTC_EHEVENT_2DCOMPLETE) },
	{ MKTC_EHEVENT_MTE_DRAIN_COMPLETE, MKTSTR(MKTC_EHEVENT_MTE_DRAIN_COMPLETE) },

	{ MKTC_3DEVENT_3DMEMFREE, MKTSTR(MKTC_3DEVENT_3DMEMFREE) },
	{ MKTC_3DEVENT_PIXELENDRENDER, MKTSTR(MKTC_3DEVENT_PIXELENDRENDER) },
	{ MKTC_3DEVENT_ISPBREAKPOINT, MKTSTR(MKTC_3DEVENT_ISPBREAKPOINT) },
	{ MKTC_3DEVENT_END, MKTSTR(MKTC_3DEVENT_END) },
	{ MKTC_3DLB_3DMEMFREE, MKTSTR(MKTC_3DLB_3DMEMFREE) },
	{ MKTC_3DLB_PIXELENDRENDER, MKTSTR(MKTC_3DLB_PIXELENDRENDER) },
	{ MKTC_3DLB_ISPBREAKPOINT, MKTSTR(MKTC_3DLB_ISPBREAKPOINT) },
	{ MKTC_3DLB_FIND3D, MKTSTR(MKTC_3DLB_FIND3D) },
	{ MKTC_3DLB_END, MKTSTR(MKTC_3DLB_END) },

	{ MKTC_TAEVENT_TAFINISHED, MKTSTR(MKTC_TAEVENT_TAFINISHED) },
	{ MKTC_TAEVENT_END, MKTSTR(MKTC_TAEVENT_END) },
	{ MKTC_TALB_TAFINISHED, MKTSTR(MKTC_TALB_TAFINISHED) },
	{ MKTC_TALB_FINDTA, MKTSTR(MKTC_TALB_FINDTA) },
	{ MKTC_TALB_END, MKTSTR(MKTC_TALB_END) },

	{ MKTC_CRRL_WRITEOPSBLOCKED, MKTSTR(MKTC_CRRL_WRITEOPSBLOCKED) },
	{ MKTC_CRRL_READOPSBLOCKED, MKTSTR(MKTC_CRRL_READOPSBLOCKED) },
	{ MKTC_CRRL_FOUNDRENDER, MKTSTR(MKTC_CRRL_FOUNDRENDER) },
	{ MKTC_CRRL_NORENDER, MKTSTR(MKTC_CRRL_NORENDER) },
	{ MKTC_CRRL_TARC_DIFFERENT, MKTSTR(MKTC_CRRL_TARC_DIFFERENT) },
	{ MKTC_FINDRENDER_BRN_23378, MKTSTR(MKTC_FINDRENDER_BRN_23378) },
	{ MKTC_CRRL_BLOCKEDRC, MKTSTR(MKTC_CRRL_BLOCKEDRC) },
	{ MKTC_CRRL_BLOCKEDRTDATA, MKTSTR(MKTC_CRRL_BLOCKEDRTDATA) },
	{ MKTC_CRRL_CONTEXT_SUSPENDED, MKTSTR(MKTC_CRRL_CONTEXT_SUSPENDED) },
	{ MKTC_CRRL_TAWAITINGFORMEM, MKTSTR(MKTC_CRRL_TAWAITINGFORMEM) },
	{ MKTC_CRRL_TAOOMBUTPRIOINV, MKTSTR(MKTC_CRRL_TAOOMBUTPRIOINV) },

	{ MKTC_KICKRENDER_START, MKTSTR(MKTC_KICKRENDER_START) },
	{ MKTC_KICKRENDER_OVERLAP, MKTSTR(MKTC_KICKRENDER_OVERLAP) },
	{ MKTC_KICKRENDER_ISP_START, MKTSTR(MKTC_KICKRENDER_ISP_START) },
	{ MKTC_KICKRENDER_RESUME, MKTSTR(MKTC_KICKRENDER_RESUME) },
	{ MKTC_KICKRENDER_CONFIG_REGION_HDRS, MKTSTR(MKTC_KICKRENDER_CONFIG_REGION_HDRS) },
	{ MKTC_KICKRENDER_END, MKTSTR(MKTC_KICKRENDER_END) },
	{ MKTC_KICKRENDER_RENDERCONTEXT, MKTSTR(MKTC_KICKRENDER_RENDERCONTEXT) },
	{ MKTC_KICKRENDER_RTDATA, MKTSTR(MKTC_KICKRENDER_RTDATA) },
	{ MKTC_KICKRENDER_PID, MKTSTR(MKTC_KICKRENDER_PID) },

	{ MKTC_RENDERFINISHED_START, MKTSTR(MKTC_RENDERFINISHED_START) },
	{ MKTC_RF_START_NEXT_MT, MKTSTR(MKTC_RF_START_NEXT_MT) },
	{ MKTC_RF_ALL_MTS_DONE, MKTSTR(MKTC_RF_ALL_MTS_DONE) },
	{ MKTC_RENDERFINISHED_END, MKTSTR(MKTC_RENDERFINISHED_END) },
	{ MKTC_VISQUERY_START, MKTSTR(MKTC_VISQUERY_START) },
	{ MKTC_VISQUERY_END, MKTSTR(MKTC_VISQUERY_END) },
	{ MKTC_TRANSFERRENDERFINISHED_START, MKTSTR(MKTC_TRANSFERRENDERFINISHED_START) },
	{ MKTC_TRANSFERRENDERFINISHED_END, MKTSTR(MKTC_TRANSFERRENDERFINISHED_END) },
	{ MKTC_TRF_UPDATESTATUSVALS, MKTSTR(MKTC_TRF_UPDATESTATUSVALS) },
	{ MKTC_TRF_UPDATESTATUSVALS_DONE, MKTSTR(MKTC_TRF_UPDATESTATUSVALS_DONE) },

	{ MKTC_PIXELENDRENDER_START, MKTSTR(MKTC_PIXELENDRENDER_START) },
	{ MKTC_PIXELENDRENDER_AFTERLOCK, MKTSTR(MKTC_PIXELENDRENDER_AFTERLOCK) },
	{ MKTC_PIXELENDRENDER_END, MKTSTR(MKTC_PIXELENDRENDER_END) },
	{ MKTC_PIXELENDRENDER_TLQEND, MKTSTR(MKTC_PIXELENDRENDER_TLQEND) },

	{ MKTC_3DMEMFREE_START, MKTSTR(MKTC_3DMEMFREE_START) },
	{ MKTC_3DMEMFREE_AFTERLOCK, MKTSTR(MKTC_3DMEMFREE_AFTERLOCK) },
	{ MKTC_3DMEMFREE_TESTEOR, MKTSTR(MKTC_3DMEMFREE_TESTEOR) },
	{ MKTC_3DMEMFREE_END, MKTSTR(MKTC_3DMEMFREE_END) },

	{ MKTC_KICKTA_START, MKTSTR(MKTC_KICKTA_START) },
	{ MKTC_KICKTA_OVERLAP, MKTSTR(MKTC_KICKTA_OVERLAP) },
	{ MKTC_KICKTA_RESETCONTEXT, MKTSTR(MKTC_KICKTA_RESETCONTEXT) },
	{ MKTC_KICKTA_VDM_START, MKTSTR(MKTC_KICKTA_VDM_START) },
	{ MKTC_KICKTA_END, MKTSTR(MKTC_KICKTA_END) },
	{ MKTC_KICKTA_RENDERCONTEXT, MKTSTR(MKTC_KICKTA_RENDERCONTEXT) },
	{ MKTC_KICKTA_RTDATA, MKTSTR(MKTC_KICKTA_RTDATA) },
	{ MKTC_KICKTA_RESET_VDMCSSTATUS, MKTSTR(MKTC_KICKTA_RESET_VDMCSSTATUS) },
	{ MKTC_KICKTA_RESET_BUFFERS, MKTSTR(MKTC_KICKTA_RESET_BUFFERS) },
	{ MKTC_KICKTA_PID, MKTSTR(MKTC_KICKTA_PID) },
	{ MKTC_KICKTA_TACMD_DEBUG, MKTSTR(MKTC_KICKTA_TACMD_DEBUG) },
	{ MKTC_KICKTA_FREECONTEXT, MKTSTR(MKTC_KICKTA_FREECONTEXT) },
	{ MKTC_KICKTA_PIM_PATCHING, MKTSTR(MKTC_KICKTA_PIM_PATCHING) },

	{ MKTC_KICKTA_CHKPT_START_DUMMY_CS, MKTSTR(MKTC_KICKTA_CHKPT_START_DUMMY_CS) },
	{ MKTC_KICKTA_CHKPT_START_DUMMY_TAK, MKTSTR(MKTC_KICKTA_CHKPT_START_DUMMY_TAK) },
	{ MKTC_KICKTA_CHKPT_WAIT_FOR_DUMMY_KICK, MKTSTR(MKTC_KICKTA_CHKPT_WAIT_FOR_DUMMY_KICK) },
	{ MKTC_KICKTA_CHKPT_WAIT_NEXT_CORE, MKTSTR(MKTC_KICKTA_CHKPT_WAIT_NEXT_CORE) },
	{ MKTC_KICKTA_CHKPT_RESET_COMPLETE, MKTSTR(MKTC_KICKTA_CHKPT_RESET_COMPLETE) },
	{ MKTC_KICKTA_CHKPT_CHECK_SWITCH, MKTSTR(MKTC_KICKTA_CHKPT_CHECK_SWITCH) },

	{ MKTC_HOSTKICK_START, MKTSTR(MKTC_HOSTKICK_START) },
	{ MKTC_HOSTKICK_END, MKTSTR(MKTC_HOSTKICK_END) },
	{ MKTC_HOSTKICK_PROCESS_QUEUES_END, MKTSTR(MKTC_HOSTKICK_PROCESS_QUEUES_END) },
	{ MKTC_HOSTKICK_2D, MKTSTR(MKTC_HOSTKICK_2D) },
	{ MKTC_HOSTKICK_TRANSFER, MKTSTR(MKTC_HOSTKICK_TRANSFER) },
	{ MKTC_HOSTKICK_TA, MKTSTR(MKTC_HOSTKICK_TA) },
	{ MKTC_HOSTKICK_PROCESS_QUEUES, MKTSTR(MKTC_HOSTKICK_PROCESS_QUEUES) },
	{ MKTC_HOSTKICK_RESUME, MKTSTR(MKTC_HOSTKICK_RESUME) },
	{ MKTC_HOSTKICK_POWEROFF, MKTSTR(MKTC_HOSTKICK_POWEROFF) },
	{ MKTC_HOSTKICK_IDLE, MKTSTR(MKTC_HOSTKICK_IDLE) },
	{ MKTC_HOSTKICK_CTXSUSPEND, MKTSTR(MKTC_HOSTKICK_CTXSUSPEND) },
	{ MKTC_HOSTKICK_CTXRESUME, MKTSTR(MKTC_HOSTKICK_CTXRESUME) },

	{ MKTC_TIMER_POTENTIAL_TA_LOCKUP, MKTSTR(MKTC_TIMER_POTENTIAL_TA_LOCKUP) },
	{ MKTC_TIMER_POTENTIAL_3D_LOCKUP, MKTSTR(MKTC_TIMER_POTENTIAL_3D_LOCKUP) },
	{ MKTC_TIMER_CTAL_START, MKTSTR(MKTC_TIMER_CTAL_START) },
	{ MKTC_TIMER_CTAL_END, MKTSTR(MKTC_TIMER_CTAL_END) },
	{ MKTC_TIMER_C3DL_START, MKTSTR(MKTC_TIMER_C3DL_START) },
	{ MKTC_TIMER_C3DL_END, MKTSTR(MKTC_TIMER_C3DL_END) },
	{ MKTC_TIMER_LOCKUP, MKTSTR(MKTC_TIMER_LOCKUP) },
	{ MKTC_TIMER_NOT_TA_LOCKUP, MKTSTR(MKTC_TIMER_NOT_TA_LOCKUP) },
	{ MKTC_TIMER_NOT_3D_LOCKUP, MKTSTR(MKTC_TIMER_NOT_3D_LOCKUP) },
	{ MKTC_TIMER_2D_LOCKUP, MKTSTR(MKTC_TIMER_2D_LOCKUP) },
	{ MKTC_TIMER_POTENTIAL_2D_LOCKUP, MKTSTR(MKTC_TIMER_POTENTIAL_2D_LOCKUP) },
	{ MKTC_TIMER_C2DL_START, MKTSTR(MKTC_TIMER_C2DL_START) },
	{ MKTC_TIMER_C2DL_END, MKTSTR(MKTC_TIMER_C2DL_END) },
	{ MKTC_TIMER_NOT_2D_LOCKUP, MKTSTR(MKTC_TIMER_NOT_2D_LOCKUP) },
	{ MKTC_TIMER_ABORTALL, MKTSTR(MKTC_TIMER_ABORTALL) },
	{ MKTC_TIMER_END, MKTSTR(MKTC_TIMER_END) },

	{ MKTC_HWR_START, MKTSTR(MKTC_HWR_START) },
	{ MKTC_HWR_END, MKTSTR(MKTC_HWR_END) },
	{ MKTC_HWR_HKS, MKTSTR(MKTC_HWR_HKS) },
	{ MKTC_HWR_PRL, MKTSTR(MKTC_HWR_PRL) },
	{ MKTC_HWR_PRL_DP, MKTSTR(MKTC_HWR_PRL_DP) },
	{ MKTC_HWR_CRL, MKTSTR(MKTC_HWR_CRL) },
	{ MKTC_HWR_CRL_DP, MKTSTR(MKTC_HWR_CRL_DP) },
	{ MKTC_HWR_TRL, MKTSTR(MKTC_HWR_TRL) },
	{ MKTC_HWR_TRL_DP, MKTSTR(MKTC_HWR_TRL_DP) },
	{ MKTC_HWR_ISC, MKTSTR(MKTC_HWR_ISC) },
	{ MKTC_HWR_2DL, MKTSTR(MKTC_HWR_2DL) },

	{ MKTC_URSV_START, MKTSTR(MKTC_URSV_START) },
	{ MKTC_URSV_UPDATEWRITEOPS, MKTSTR(MKTC_URSV_UPDATEWRITEOPS) },
	{ MKTC_URSV_UPDATESTATUSVALS, MKTSTR(MKTC_URSV_UPDATESTATUSVALS) },
	{ MKTC_URSV_UPDATESTATUSVALS_DONE, MKTSTR(MKTC_URSV_UPDATESTATUSVALS_DONE) },
	{ MKTC_URSV_END, MKTSTR(MKTC_URSV_END) },

	{ MKTC_STORETACONTEXT_START, MKTSTR(MKTC_STORETACONTEXT_START) },
	{ MKTC_STORETACONTEXT_END, MKTSTR(MKTC_STORETACONTEXT_END) },
	{ MKTC_LOADTACONTEXT_START, MKTSTR(MKTC_LOADTACONTEXT_START) },
	{ MKTC_LOADTACONTEXT_END, MKTSTR(MKTC_LOADTACONTEXT_END) },
	{ MKTC_STORE3DCONTEXT_START, MKTSTR(MKTC_STORE3DCONTEXT_START) },
	{ MKTC_STORE3DCONTEXT_END, MKTSTR(MKTC_STORE3DCONTEXT_END) },
	{ MKTC_LOAD3DCONTEXT_START, MKTSTR(MKTC_LOAD3DCONTEXT_START) },
	{ MKTC_LOAD3DCONTEXT_END, MKTSTR(MKTC_LOAD3DCONTEXT_END) },

	{ MKTC_FINDTA_POWERREQUEST, MKTSTR(MKTC_FINDTA_POWERREQUEST) },
	{ MKTC_FINDTA_TA3D_OVERLAP_BLOCKED, MKTSTR(MKTC_FINDTA_TA3D_OVERLAP_BLOCKED) },
	{ MKTC_FINDTA_RTDATA_RENDERING, MKTSTR(MKTC_FINDTA_RTDATA_RENDERING) },
	{ MKTC_FINDTA_3DRC_DIFFERENT, MKTSTR(MKTC_FINDTA_3DRC_DIFFERENT) },
	{ MKTC_FINDTA_WRITEOPSBLOCKED, MKTSTR(MKTC_FINDTA_WRITEOPSBLOCKED) },
	{ MKTC_FINDTA_READOPSBLOCKED, MKTSTR(MKTC_FINDTA_READOPSBLOCKED) },
	{ MKTC_FINDTA_RESIZE_PB, MKTSTR(MKTC_FINDTA_RESIZE_PB) },
	{ MKTC_FINDTA_RESIZE_PB_BLOCKED, MKTSTR(MKTC_FINDTA_RESIZE_PB_BLOCKED) },
	{ MKTC_FINDTA_SHRINK_PB, MKTSTR(MKTC_FINDTA_SHRINK_PB) },
	{ MKTC_FINDTA_TAPB_DIFFERENT, MKTSTR(MKTC_FINDTA_TAPB_DIFFERENT) },
	{ MKTC_FINDTA_TACONTEXT_DIFFERENT, MKTSTR(MKTC_FINDTA_TACONTEXT_DIFFERENT) },
	{ MKTC_FINDTA_TA2D_OVERLAP_BLOCKED, MKTSTR(MKTC_FINDTA_TA2D_OVERLAP_BLOCKED) },
	{ MKTC_FINDTA_CONTEXT_SUSPENDED, MKTSTR(MKTC_FINDTA_CONTEXT_SUSPENDED) },
	{ MKTC_FINDTA_SRC_READOPSBLOCKED, MKTSTR(MKTC_FINDTA_SRC_READOPSBLOCKED) },
	{ MKTC_FINDTA_SRC_WRITEOPSBLOCKED, MKTSTR(MKTC_FINDTA_SRC_WRITEOPSBLOCKED) },

	{ MKTC_CTRL_SRCREADOPSBLOCKED, MKTSTR(MKTC_CTRL_SRCREADOPSBLOCKED) },
	{ MKTC_CTRL_SRCWRITEOPSBLOCKED, MKTSTR(MKTC_CTRL_SRCWRITEOPSBLOCKED) },
	{ MKTC_CTRL_DSTREADOPSBLOCKED, MKTSTR(MKTC_CTRL_DSTREADOPSBLOCKED) },
	{ MKTC_CTRL_DSTWRITEOPSBLOCKED, MKTSTR(MKTC_CTRL_DSTWRITEOPSBLOCKED) },
	{ MKTC_CTRL_TARC_DIFFERENT, MKTSTR(MKTC_CTRL_TARC_DIFFERENT) },
	{ MKTC_CTRL_CONTEXT_SUSPENDED, MKTSTR(MKTC_CTRL_CONTEXT_SUSPENDED) },

	{ MKTC_DPTA_START, MKTSTR(MKTC_DPTA_START) },
	{ MKTC_DPTA_UPDATESTATUSVALS, MKTSTR(MKTC_DPTA_UPDATESTATUSVALS) },
	{ MKTC_DPTA_UPDATESTATUSVALS_DONE, MKTSTR(MKTC_DPTA_UPDATESTATUSVALS_DONE) },
	{ MKTC_DPTA_NORENDER, MKTSTR(MKTC_DPTA_NORENDER) },
	{ MKTC_DPTA_MEMFREE, MKTSTR(MKTC_DPTA_MEMFREE) },
	{ MKTC_DPTA_INC_COMPLETECOUNT, MKTSTR(MKTC_DPTA_INC_COMPLETECOUNT) },

	{ MKTC_INVALDC, MKTSTR(MKTC_INVALDC) },
	{ MKTC_INVALPT, MKTSTR(MKTC_INVALPT) },
	{ MKTC_INVALSLC, MKTSTR(MKTC_INVALSLC) },
	{ MKTC_INVALDATA, MKTSTR(MKTC_INVALDATA) },

	{ MKTC_RESTARTTA, MKTSTR(MKTC_RESTARTTA) },
	{ MKTC_CSABORTNONGBL, MKTSTR(MKTC_CSABORTNONGBL) },
	{ MKTC_CSABORTALL, MKTSTR(MKTC_CSABORTALL) },
	{ MKTC_CSRENDERINPROGRESS, MKTSTR(MKTC_CSRENDERINPROGRESS) },
	{ MKTC_TATERMRENDERINPROGRESS, MKTSTR(MKTC_TATERMRENDERINPROGRESS) },
	{ MKTC_RESTARTTANORENDER, MKTSTR(MKTC_RESTARTTANORENDER) },
	{ MKTC_SPM_KICKRENDER, MKTSTR(MKTC_SPM_KICKRENDER) },
	{ MKTC_SPM_RESUME_ABORTCOMPLETE, MKTSTR(MKTC_SPM_RESUME_ABORTCOMPLETE) },
	{ MKTC_RESUMEVDM, MKTSTR(MKTC_RESUMEVDM) },
	{ MKTC_REMOVE_RESERVE_MEM, MKTSTR(MKTC_REMOVE_RESERVE_MEM) },
	{ MKTC_INCREASEZLSTHRESHOLD, MKTSTR(MKTC_INCREASEZLSTHRESHOLD) },
	{ MKTC_CSFORCEABORTALL, MKTSTR(MKTC_CSFORCEABORTALL) },

	{ MKTC_DUMMY_DEPTH, MKTSTR(MKTC_DUMMY_DEPTH) },
	{ MKTC_DUMMY_DEPTH_CS, MKTSTR(MKTC_DUMMY_DEPTH_CS) },

	{ MKTC_MTETE_OOM, MKTSTR(MKTC_MTETE_OOM) },
	{ MKTC_MTETE_OOM_FIRST_STORE_REF, MKTSTR(MKTC_MTETE_OOM_FIRST_STORE_REF) },
	{ MKTC_MERGE_STATE_TABLES, MKTSTR(MKTC_MERGE_STATE_TABLES) },
	{ MKTC_NO_PAGES_LEFT_FOR_23055, MKTSTR(MKTC_NO_PAGES_LEFT_FOR_23055) },
	{ MKTC_NO_STATE_MODS, MKTSTR(MKTC_NO_STATE_MODS) },
	{ MKTC_FIND_MTE_PAGE_IN_STATE, MKTSTR(MKTC_FIND_MTE_PAGE_IN_STATE) },
	{ MKTC_MTE_PAGE_FOUND, MKTSTR(MKTC_MTE_PAGE_FOUND) },
	{ MKTC_MOVE_MTE_PAGE_TO_TA_STATE, MKTSTR(MKTC_MOVE_MTE_PAGE_TO_TA_STATE) },
	{ MKTC_MOVE_MTE_PAGE_TO_TA_STATE_END, MKTSTR(MKTC_MOVE_MTE_PAGE_TO_TA_STATE_END) },
	{ MKTC_ZERO_ZLS_THRESHOLD, MKTSTR(MKTC_ZERO_ZLS_THRESHOLD) },
	{ MKTC_RESTORE_ZLS_THRESHOLD, MKTSTR(MKTC_RESTORE_ZLS_THRESHOLD) },
	{ MKTC_FIND_MTE_PAGE_IN_CSM, MKTSTR(MKTC_FIND_MTE_PAGE_IN_CSM) },
	{ MKTC_REISSUE_MTE_PAGE, MKTSTR(MKTC_REISSUE_MTE_PAGE) },
	{ MKTC_REISSUE_MTE_PAGE_REQUIRED, MKTSTR(MKTC_REISSUE_MTE_PAGE_REQUIRED) },
	{ MKTC_REISSUE_MTE_PAGE_END, MKTSTR(MKTC_REISSUE_MTE_PAGE_END) },
	{ MKTC_RESET_TE_PSG, MKTSTR(MKTC_RESET_TE_PSG) },

	{ MKTC_OOM_WRITEOPSBLOCKED, MKTSTR(MKTC_OOM_WRITEOPSBLOCKED) },
	{ MKTC_OOM_READOPSBLOCKED, MKTSTR(MKTC_OOM_READOPSBLOCKED) },
	{ MKTC_OOM_SRC_WRITEOPSBLOCKED, MKTSTR(MKTC_OOM_SRC_WRITEOPSBLOCKED) },
	{ MKTC_OOM_SRC_READOPSBLOCKED, MKTSTR(MKTC_OOM_SRC_READOPSBLOCKED) },
	{ MKTC_OOM_SPM_DEADLOCK, MKTSTR(MKTC_OOM_SPM_DEADLOCK) },
	{ MKTC_OOM_SPM_DEADLOCK_MEM_ADDED, MKTSTR(MKTC_OOM_SPM_DEADLOCK_MEM_ADDED) },
	{ MKTC_BRN27311_RESET, MKTSTR(MKTC_BRN27311_RESET) },
	{ MKTC_SPM_INVALID_ZLSCONFIG, MKTSTR(MKTC_SPM_INVALID_ZLSCONFIG) },

	{ MKTC_SPM_ALREADY_DRAINED, MKTSTR(MKTC_SPM_ALREADY_DRAINED) },
	{ MKTC_DRAIN_COMPLETE, MKTSTR(MKTC_DRAIN_COMPLETE) },
	{ MKTC_DRAIN_SET_FLAG, MKTSTR(MKTC_DRAIN_SET_FLAG) },

	{ MKTC_OOM_TYPE_MT, MKTSTR(MKTC_OOM_TYPE_MT) },
	{ MKTC_OOM_TYPE_GLOBAL, MKTSTR(MKTC_OOM_TYPE_GLOBAL) },
	{ MKTC_OOM_CAUSE_GBL_OOM, MKTSTR(MKTC_OOM_CAUSE_GBL_OOM) },

	{ MKTC_CHECK_MTE_PAGE_REISSUE, MKTSTR(MKTC_CHECK_MTE_PAGE_REISSUE) },
	{ MKTC_CPRI_VALID_ENTRIES, MKTSTR(MKTC_CPRI_VALID_ENTRIES) },
	{ MKTC_CPRI_STORE_DPLIST, MKTSTR(MKTC_CPRI_STORE_DPLIST) },
	{ MKTC_CPRI_STORE_OTPM_CSM, MKTSTR(MKTC_CPRI_STORE_OTPM_CSM) },
	{ MKTC_CPRI_ABORT_MT_IDX, MKTSTR(MKTC_CPRI_ABORT_MT_IDX) },
	{ MKTC_CPRI_ABORT_CORE_IDX, MKTSTR(MKTC_CPRI_ABORT_CORE_IDX) },
	{ MKTC_CPRI_CSM_TABLE_DATA, MKTSTR(MKTC_CPRI_CSM_TABLE_DATA) },
	{ MKTC_CPRI_PIM_DATA, MKTSTR(MKTC_CPRI_PIM_DATA) },
	{ MKTC_CPRI_DO_CIRCULAR_TEST, MKTSTR(MKTC_CPRI_DO_CIRCULAR_TEST) },

	{ MKTC_CPRI_WRITE_ENTRIES, MKTSTR(MKTC_CPRI_WRITE_ENTRIES) },

	{ MKTC_MTE_ENTRY_NOT_IN_ANY_LIST, MKTSTR(MKTC_MTE_ENTRY_NOT_IN_ANY_LIST) },

	{ MKTC_SPMAC_IGNORE_TERMINATE, MKTSTR(MKTC_SPMAC_IGNORE_TERMINATE) },

	{ MKTC_SPMAC_REQUEST_3D_TIMEOUT, MKTSTR(MKTC_SPMAC_REQUEST_3D_TIMEOUT) },
	{ MKTC_SPMAC_3D_TIMEOUT_COMPLETE, MKTSTR(MKTC_SPMAC_3D_TIMEOUT_COMPLETE) },

/* PB Load/store status */
	{ MKTC_LOADTAPB_START, MKTSTR(MKTC_LOADTAPB_START) },
	{ MKTC_LOADTAPB_END, MKTSTR(MKTC_LOADTAPB_END) },
	{ MKTC_STORETAPB_START, MKTSTR(MKTC_STORETAPB_START) },
	{ MKTC_STORETAPB_END, MKTSTR(MKTC_STORETAPB_END) },
	{ MKTC_LOAD3DPB_START, MKTSTR(MKTC_LOAD3DPB_START) },
	{ MKTC_LOAD3DPB_END, MKTSTR(MKTC_LOAD3DPB_END) },
	{ MKTC_STORE3DPB_START, MKTSTR(MKTC_STORE3DPB_START) },
	{ MKTC_STORE3DPB_END, MKTSTR(MKTC_STORE3DPB_END) },
	{ MKTC_LOADTAPB_PAGETABLE_DONE, MKTSTR(MKTC_LOADTAPB_PAGETABLE_DONE) },
	{ MKTC_LOAD3DPB_PAGETABLE_DONE, MKTSTR(MKTC_LOAD3DPB_PAGETABLE_DONE) },

	{ MKTC_TIMER_RC_CLEANUP, MKTSTR(MKTC_TIMER_RC_CLEANUP) },
	{ MKTC_TIMER_RC_CLEANUP_COMPLETE, MKTSTR(MKTC_TIMER_RC_CLEANUP_COMPLETE) },
	{ MKTC_TIMER_RT_CLEANUP, MKTSTR(MKTC_TIMER_RT_CLEANUP) },
	{ MKTC_TIMER_RT_CLEANUP_COMPLETE, MKTSTR(MKTC_TIMER_RT_CLEANUP_COMPLETE) },
	{ MKTC_TIMER_RT_CLEANUP_PENDING, MKTSTR(MKTC_TIMER_RT_CLEANUP_PENDING) },
	{ MKTC_TIMER_RT_CLEANUP_TIDYPARTIALLIST, MKTSTR(MKTC_TIMER_RT_CLEANUP_TIDYPARTIALLIST) },
	{ MKTC_TIMER_TC_CLEANUP, MKTSTR(MKTC_TIMER_TC_CLEANUP) },
	{ MKTC_TIMER_TC_CLEANUP_COMPLETE, MKTSTR(MKTC_TIMER_TC_CLEANUP_COMPLETE) },
	{ MKTC_TIMER_2DC_CLEANUP, MKTSTR(MKTC_TIMER_2DC_CLEANUP) },
	{ MKTC_TIMER_2DC_CLEANUP_COMPLETE, MKTSTR(MKTC_TIMER_2DC_CLEANUP_COMPLETE) },
	{ MKTC_TIMER_SHAREDPBDESC_CLEANUP, MKTSTR(MKTC_TIMER_SHAREDPBDESC_CLEANUP) },

	{ MKTC_TIMER_ISP_SWITCH_POTENTIAL_LOCKUP, MKTSTR(MKTC_TIMER_ISP_SWITCH_POTENTIAL_LOCKUP) },
	{ MKTC_TIMER_ISP_SWITCH_FORCE_SWITCH, MKTSTR(MKTC_TIMER_ISP_SWITCH_FORCE_SWITCH) },

	{ MKTC_UTSO_UPDATEREADOPS, MKTSTR(MKTC_UTSO_UPDATEREADOPS) },
	{ MKTC_UTSO_UPDATEWRITEOPS, MKTSTR(MKTC_UTSO_UPDATEWRITEOPS) },

	{ MKTC_TAFINISHED_UPDATESTATUSVALS, MKTSTR(MKTC_TAFINISHED_UPDATESTATUSVALS) },
	{ MKTC_TAFINISHED_UPDATESTATUSVALS_DONE, MKTSTR(MKTC_TAFINISHED_UPDATESTATUSVALS_DONE) },
	{ MKTC_TAFINISHED_NORENDER, MKTSTR(MKTC_TAFINISHED_NORENDER) },
	{ MKTC_TAFINISHED_LASTKICK, MKTSTR(MKTC_TAFINISHED_LASTKICK) },
	{ MKTC_TAFINISHED_FINDRENDER, MKTSTR(MKTC_TAFINISHED_FINDRENDER) },
	{ MKTC_TAFINISHED_FINDTA, MKTSTR(MKTC_TAFINISHED_FINDTA) },
	{ MKTC_TAFINISHED_END, MKTSTR(MKTC_TAFINISHED_END) },
	{ MKTC_TAF_SPM_DEADLOCK_MEM_REMOVED, MKTSTR(MKTC_TAF_SPM_DEADLOCK_MEM_REMOVED) },
	{ MKTC_TAF_RESERVE_MEM, MKTSTR(MKTC_TAF_RESERVE_MEM) },
	{ MKTC_TAF_RESERVE_MEM_REQUEST_RENDER, MKTSTR(MKTC_TAF_RESERVE_MEM_REQUEST_RENDER) },
	{ MKTC_TAF_RESERVE_FREE_RENDER_FINISHED, MKTSTR(MKTC_TAF_RESERVE_FREE_RENDER_FINISHED) },
	{ MKTC_TAF_RESERVE_FREE_DUMMY_RENDER, MKTSTR(MKTC_TAF_RESERVE_FREE_DUMMY_RENDER) },
	{ MKTC_TAF_DEBUG_SAS, MKTSTR(MKTC_TAF_DEBUG_SAS) },
	{ MKTC_TAFINISHED_NOCONTEXTSWITCH, MKTSTR(MKTC_TAFINISHED_NOCONTEXTSWITCH) },

	{ MKTC_TAFINISHED_TERM_COMPLETE_START, MKTSTR(MKTC_TAFINISHED_TERM_COMPLETE_START) },
	{ MKTC_TAFINISHED_TERM_COMPLETE_END, MKTSTR(MKTC_TAFINISHED_TERM_COMPLETE_END) },

	{ MKTC_TAFINISHED_ZERO_TAILPTRS, MKTSTR(MKTC_TAFINISHED_ZERO_TAILPTRS) },

	{ MKTC_2DEVENT_2DCOMPLETE, MKTSTR(MKTC_2DEVENT_2DCOMPLETE) },
	{ MKTC_2DEVENT_END, MKTSTR(MKTC_2DEVENT_END) },
	{ MKTC_2DLB_2DCOMPLETE, MKTSTR(MKTC_2DLB_2DCOMPLETE) },
	{ MKTC_2DLB_FIND2D, MKTSTR(MKTC_2DLB_FIND2D) },
	{ MKTC_2DLB_END, MKTSTR(MKTC_2DLB_END) },
	{ MKTC_2DCOMPLETE_START, MKTSTR(MKTC_2DCOMPLETE_START) },
	{ MKTC_2DCOMPLETE_END, MKTSTR(MKTC_2DCOMPLETE_END) },
	{ MKTC_KICK2D_START, MKTSTR(MKTC_KICK2D_START) },
	{ MKTC_KICK2D_END, MKTSTR(MKTC_KICK2D_END) },
	{ MKTC_DUMMYPROC2D, MKTSTR(MKTC_DUMMYPROC2D) },
	{ MKTC_FTD_SRCREADOPSBLOCKED, MKTSTR(MKTC_FTD_SRCREADOPSBLOCKED) },
	{ MKTC_FTD_SRCWRITEOPSBLOCKED, MKTSTR(MKTC_FTD_SRCWRITEOPSBLOCKED) },
	{ MKTC_FTD_DSTREADOPSBLOCKED, MKTSTR(MKTC_FTD_DSTREADOPSBLOCKED) },
	{ MKTC_FTD_DSTWRITEOPSBLOCKED, MKTSTR(MKTC_FTD_DSTWRITEOPSBLOCKED) },
	{ MKTC_FTD_TA2D_OVERLAP_BLOCKED, MKTSTR(MKTC_FTD_TA2D_OVERLAP_BLOCKED) },
	{ MKTC_U2DSO_UPDATEREADOPS, MKTSTR(MKTC_U2DSO_UPDATEREADOPS) },
	{ MKTC_U2DSO_UPDATEWRITEOPS, MKTSTR(MKTC_U2DSO_UPDATEWRITEOPS) },
	{ MKTC_FTD_TAOPSBLOCKED, MKTSTR(MKTC_FTD_TAOPSBLOCKED) },
	{ MKTC_KICK2D_2DSLAVEPORT, MKTSTR(MKTC_KICK2D_2DSLAVEPORT) },
	{ MKTC_KICK2D_2DSLAVEPORT_DONE, MKTSTR(MKTC_KICK2D_2DSLAVEPORT_DONE) },
	{ MKTC_FTD_CONTEXT_SUSPENDED, MKTSTR(MKTC_FTD_CONTEXT_SUSPENDED) },
	{ MKTC_KICK2D_PID, MKTSTR(MKTC_KICK2D_PID) },
	{ MKTC_FIND2D_ADDR_SPACE_DIFFERENT, MKTSTR(MKTC_FIND2D_ADDR_SPACE_DIFFERENT) },
	{ MKTC_FTD_3DOPSBLOCKED, MKTSTR(MKTC_FTD_3DOPSBLOCKED) },

	{ MKTC_FCM_START, MKTSTR(MKTC_FCM_START) },
	{ MKTC_FCM_END, MKTSTR(MKTC_FCM_END) },

	{ MKTC_TIMER_ACTIVE_POWER, MKTSTR(MKTC_TIMER_ACTIVE_POWER) },
	{ MKTC_TIMER_POWER_3D_ACTIVE, MKTSTR(MKTC_TIMER_POWER_3D_ACTIVE) },
	{ MKTC_TIMER_POWER_TA_ACTIVE, MKTSTR(MKTC_TIMER_POWER_TA_ACTIVE) },
	{ MKTC_TIMER_POWER_2D_ACTIVE, MKTSTR(MKTC_TIMER_POWER_2D_ACTIVE) },
	{ MKTC_TIMER_POWER_PENDING_EVENTS, MKTSTR(MKTC_TIMER_POWER_PENDING_EVENTS) },
	{ MKTC_TIMER_POWER_IDLE, MKTSTR(MKTC_TIMER_POWER_IDLE) },
	{ MKTC_TIMER_POWER_OFF, MKTSTR(MKTC_TIMER_POWER_OFF) },
	{ MKTC_TIMER_POWER_CCB_ERROR, MKTSTR(MKTC_TIMER_POWER_CCB_ERROR) },
	{ MKTC_TIMER_POWER_RESTART_IMMEDIATE, MKTSTR(MKTC_TIMER_POWER_RESTART_IMMEDIATE) },

	{ MKTC_3DCONTEXT_SWITCH, MKTSTR(MKTC_3DCONTEXT_SWITCH) },
	{ MKTC_3DCONTEXT_SWITCH_END, MKTSTR(MKTC_3DCONTEXT_SWITCH_END) },

	{ MKTC_TACONTEXT_SWITCH, MKTSTR(MKTC_TACONTEXT_SWITCH) },
	{ MKTC_TACONTEXT_SWITCH_FAST, MKTSTR(MKTC_TACONTEXT_SWITCH_FAST) },
	{ MKTC_TACONTEXT_SWITCH_END, MKTSTR(MKTC_TACONTEXT_SWITCH_END) },

	{ MKTC_GETMISCINFO_MEMREAD_START, MKTSTR(MKTC_GETMISCINFO_MEMREAD_START) },
	{ MKTC_GETMISCINFO_MEMREAD_END, MKTSTR(MKTC_GETMISCINFO_MEMREAD_END) },
	{ MKTC_GETMISCINFO_MEMWRITE_START, MKTSTR(MKTC_GETMISCINFO_MEMWRITE_START) },
	{ MKTC_GETMISCINFO_MEMWRITE_END, MKTSTR(MKTC_GETMISCINFO_MEMWRITE_END) },

	{ MKTC_HALTTA, MKTSTR(MKTC_HALTTA) },
	{ MKTC_HTA_SET_FLAG, MKTSTR(MKTC_HTA_SET_FLAG) },
	{ MKTC_HTA_SAVE_COMPLEX_PTR, MKTSTR(MKTC_HTA_SAVE_COMPLEX_PTR) },
	{ MKTC_HALTTA_END, MKTSTR(MKTC_HALTTA_END) },

	{ MKTC_RESUMETA, MKTSTR(MKTC_RESUMETA) },
	{ MKTC_RTA_CONTEXT_LOADED, MKTSTR(MKTC_RTA_CONTEXT_LOADED) },
	{ MKTC_RTA_MTE_STATE_KICKED, MKTSTR(MKTC_RTA_MTE_STATE_KICKED) },
	{ MKTC_RTA_CMPLX_GEOM_PRESENT, MKTSTR(MKTC_RTA_CMPLX_GEOM_PRESENT) },
	{ MKTC_RTA_CMPLX_STATE_KICKED, MKTSTR(MKTC_RTA_CMPLX_STATE_KICKED) },
	{ MKTC_RTA_CHECK_NEXT_SA_PROG, MKTSTR(MKTC_RTA_CHECK_NEXT_SA_PROG) },
	{ MKTC_RTA_CORE_COMPLETED, MKTSTR(MKTC_RTA_CORE_COMPLETED) },
	{ MKTC_RTA_DEBUG_SAS, MKTSTR(MKTC_RTA_DEBUG_SAS) },
	{ MKTC_RESUMETA_END, MKTSTR(MKTC_RESUMETA_END) },

	{ MKTC_RESUME_SPMCS_START, MKTSTR(MKTC_RESUME_SPMCS_START) },
	{ MKTC_RSPMCS_OVERLAP, MKTSTR(MKTC_RSPMCS_OVERLAP) },
	{ MKTC_RSPMCS_START_PULSE, MKTSTR(MKTC_RSPMCS_START_PULSE) },
	{ MKTC_RESUME_SPMCS_END, MKTSTR(MKTC_RESUME_SPMCS_END) },

	{ MKTC_RENDERHALT, MKTSTR(MKTC_RENDERHALT) },
	{ MKTC_RH_CLEARFLAGS, MKTSTR(MKTC_RH_CLEARFLAGS) },
	{ MKTC_RH_CTRL_ADDR, MKTSTR(MKTC_RH_CTRL_ADDR) },
	{ MKTC_RH_RGN_ADDR, MKTSTR(MKTC_RH_RGN_ADDR) },
	{ MKTC_RH_EMPTY_TILE, MKTSTR(MKTC_RH_EMPTY_TILE) },
	{ MKTC_RH_EMPTY_LAST_TILE, MKTSTR(MKTC_RH_EMPTY_LAST_TILE) },
	{ MKTC_RH_3D_TIMEOUT, MKTSTR(MKTC_RH_3D_TIMEOUT) },
	{ MKTC_RH_NOT_EMPTY, MKTSTR(MKTC_RH_NOT_EMPTY) },
	{ MKTC_RH_OBJECT_COMPLETE, MKTSTR(MKTC_RH_OBJECT_COMPLETE) },
	{ MKTC_RH_STREAM_LINK, MKTSTR(MKTC_RH_STREAM_LINK) },
	{ MKTC_RH_OBJECT_INCOMPLETE, MKTSTR(MKTC_RH_OBJECT_INCOMPLETE) },
	{ MKTC_RH_PRIM_MASK_PRESENT, MKTSTR(MKTC_RH_PRIM_MASK_PRESENT) },
	{ MKTC_RH_BYTE_MASK_PRESENT, MKTSTR(MKTC_RH_BYTE_MASK_PRESENT) },
	{ MKTC_RH_BYTE_MASK_ZERO, MKTSTR(MKTC_RH_BYTE_MASK_ZERO) },
	{ MKTC_RH_PRIM_MASK_ZERO, MKTSTR(MKTC_RH_PRIM_MASK_ZERO) },
	{ MKTC_RH_INVALIDATE_OBJECTS, MKTSTR(MKTC_RH_INVALIDATE_OBJECTS) },
	{ MKTC_RH_OBJECTS_INVALIDATED, MKTSTR(MKTC_RH_OBJECTS_INVALIDATED) },
	{ MKTC_RH_DPM_RGN_PARSER_IDLE, MKTSTR(MKTC_RH_DPM_RGN_PARSER_IDLE) },
	{ MKTC_RH_NEXT_RGN_BASE, MKTSTR(MKTC_RH_NEXT_RGN_BASE) },
	{ MKTC_RH_OCC_EXIT, MKTSTR(MKTC_RH_OCC_EXIT) },
	{ MKTC_RH_STILL_RUNNING, MKTSTR(MKTC_RH_STILL_RUNNING) },
	{ MKTC_RH_CLEARMCI, MKTSTR(MKTC_RH_CLEARMCI) },
	{ MKTC_RH_EOR, MKTSTR(MKTC_RH_EOR) },
	{ MKTC_RENDERHALT_END, MKTSTR(MKTC_RENDERHALT_END) },

	{ MKTC_FIND3D_POWERREQUEST, MKTSTR(MKTC_FIND3D_POWERREQUEST) },

	{ MKTC_FIND2D_POWERREQUEST, MKTSTR(MKTC_FIND2D_POWERREQUEST) },

	{ MKTC_SPM_OOM_POWERREQUEST, MKTSTR(MKTC_SPM_OOM_POWERREQUEST) },
	{ MKTC_SPM_AC_POWERREQUEST, MKTSTR(MKTC_SPM_AC_POWERREQUEST) },
	{ MKTC_SPM_RF_POWERREQUEST, MKTSTR(MKTC_SPM_RF_POWERREQUEST) },

	{ MKTC_UKERNEL_INIT, MKTSTR(MKTC_UKERNEL_INIT) },
	{ MKTC_UKERNEL_INIT_DCS_COMPLETE, MKTSTR(MKTC_UKERNEL_INIT_DCS_COMPLETE) },
	{ MKTC_UKERNEL_INIT_VDMKICK_COMPLETE, MKTSTR(MKTC_UKERNEL_INIT_VDMKICK_COMPLETE) },

	{ MKTC_KICKTRANSFERRENDER_START, MKTSTR(MKTC_KICKTRANSFERRENDER_START) },
	{ MKTC_KICKTRANSFERRENDER_ISP_START, MKTSTR(MKTC_KICKTRANSFERRENDER_ISP_START) },
	{ MKTC_KICKTRANSFERRENDER_END, MKTSTR(MKTC_KICKTRANSFERRENDER_END) },
	{ MKTC_DUMMYPROCTRANSFER, MKTSTR(MKTC_DUMMYPROCTRANSFER) },
	{ MKTC_KTR_TQFENCE, MKTSTR(MKTC_KTR_TQFENCE) },
	{ MKTC_KICKTRANSFERRENDER_PID, MKTSTR(MKTC_KICKTRANSFERRENDER_PID) },

	{ MKTC_HOSTKICK_CLEANUP_RT, MKTSTR(MKTC_HOSTKICK_CLEANUP_RT) },
	{ MKTC_HOSTKICK_CLEANUP_RC, MKTSTR(MKTC_HOSTKICK_CLEANUP_RC) },
	{ MKTC_HOSTKICK_CLEANUP_TC, MKTSTR(MKTC_HOSTKICK_CLEANUP_TC) },
	{ MKTC_HOSTKICK_CLEANUP_2DC, MKTSTR(MKTC_HOSTKICK_CLEANUP_2DC) },
	{ MKTC_HOSTKICK_CLEANUP_PB, MKTSTR(MKTC_HOSTKICK_CLEANUP_PB) },
	{ MKTC_HOSTKICK_GETMISCINFO, MKTSTR(MKTC_HOSTKICK_GETMISCINFO) },
	{ MKTC_HOSTKICK_DATABREAKPOINT, MKTSTR(MKTC_HOSTKICK_DATABREAKPOINT) },
	{ MKTC_HOSTKICK_SETHWPERFSTATUS, MKTSTR(MKTC_HOSTKICK_SETHWPERFSTATUS) },

	{ MKTC_ZEROPC, MKTSTR(MKTC_ZEROPC) },

	{ MKTC_ASSERT_FAIL, MKTSTR(MKTC_ASSERT_FAIL) },

	{ MKTC_SDLB_ILLEGAL, MKTSTR(MKTC_SDLB_ILLEGAL) },

	{ MKTC_SPMEVENT_MEMTHRESHOLD, MKTSTR(MKTC_SPMEVENT_MEMTHRESHOLD) },
	{ MKTC_SPMEVENT_OUTOFMEM, MKTSTR(MKTC_SPMEVENT_OUTOFMEM) },
	{ MKTC_SPMEVENT_TATERMINATE, MKTSTR(MKTC_SPMEVENT_TATERMINATE) },
	{ MKTC_SPMEVENT_MTE_DRAIN_COMPLETE, MKTSTR(MKTC_SPMEVENT_MTE_DRAIN_COMPLETE) },
	{ MKTC_SPMEVENT_END, MKTSTR(MKTC_SPMEVENT_END) },
	{ MKTC_SPMLB_MEMTHRESHOLD, MKTSTR(MKTC_SPMLB_MEMTHRESHOLD) },
	{ MKTC_SPMLB_OUTOFMEM, MKTSTR(MKTC_SPMLB_OUTOFMEM) },
	{ MKTC_SPMLB_TATERMINATE, MKTSTR(MKTC_SPMLB_TATERMINATE) },
	{ MKTC_SPMLB_SPMRENDERFINSHED, MKTSTR(MKTC_SPMLB_SPMRENDERFINSHED) },
	{ MKTC_SPMLB_MTE_DRAIN_COMPLETE, MKTSTR(MKTC_SPMLB_MTE_DRAIN_COMPLETE) },
	{ MKTC_SPMLB_END, MKTSTR(MKTC_SPMLB_END) },

	{ MKTC_SPM_CHECK_MT_DEADLOCK, MKTSTR(MKTC_SPM_CHECK_MT_DEADLOCK) },
	{ MKTC_SPM_CHECK_GLOBAL_DEADLOCK, MKTSTR(MKTC_SPM_CHECK_GLOBAL_DEADLOCK) },
	{ MKTC_SPM_RESERVE_ADDED, MKTSTR(MKTC_SPM_RESERVE_ADDED) },

	{ MKTC_IBC_ILLEGAL, MKTSTR(MKTC_IBC_ILLEGAL) },

	{ MKTC_HWP_CLEARCOUNTERS, MKTSTR(MKTC_HWP_CLEARCOUNTERS) },

	{ MKTC_TA_FRAMENUM, MKTSTR(MKTC_TA_FRAMENUM) },
	{ MKTC_3D_FRAMENUM, MKTSTR(MKTC_3D_FRAMENUM) },
	{ MKTC_SPM3D_FRAMENUM, MKTSTR(MKTC_SPM3D_FRAMENUM) },

	{ MKTC_HKTA_RENDERCONTEXT, MKTSTR(MKTC_HKTA_RENDERCONTEXT) },
	{ MKTC_IDLECORE_REFCOUNT_FAIL, MKTSTR(MKTC_IDLECORE_REFCOUNT_FAIL) },

	{ MKTC_MCISTATE_NOT_CLEARED, MKTSTR(MKTC_MCISTATE_NOT_CLEARED) },


	{ MKTC_LOWERED_TO_PDS_THRESHOLD, MKTSTR(MKTC_LOWERED_TO_PDS_THRESHOLD) },
	{ MKTC_REDUCE_MAX_VTX_PARTITIONS, MKTSTR(MKTC_REDUCE_MAX_VTX_PARTITIONS) },
	{ MKTC_KTAOVERRIDE_MAX_VTX_PARTITIONS, MKTSTR(MKTC_KTAOVERRIDE_MAX_VTX_PARTITIONS) },
	{ MKTC_KTANOOVERRIDE_MAX_VTX_PARTITIONS, MKTSTR(MKTC_KTANOOVERRIDE_MAX_VTX_PARTITIONS) },


	{ MKTC_IPRB_NORENDERDETAILS, MKTSTR(MKTC_IPRB_NORENDERDETAILS) },
	{ MKTC_IPRB_HAVERENDERDETAILS, MKTSTR(MKTC_IPRB_HAVERENDERDETAILS) },

	{ MKTC_RENDER_OUT_OF_ORDER, MKTSTR(MKTC_RENDER_OUT_OF_ORDER) },
	{ MKTC_RENDER_NOT_OUT_OF_ORDER, MKTSTR(MKTC_RENDER_NOT_OUT_OF_ORDER) },

	{ MKTC_ZLS_IDLE_BEGIN, MKTSTR(MKTC_ZLS_IDLE_BEGIN) },
	{ MKTC_ZLS_ISP_CLK_GATING_EN, MKTSTR(MKTC_ZLS_ISP_CLK_GATING_EN) },
	{ MKTC_ZLS_IDLE_END, MKTSTR(MKTC_ZLS_IDLE_END) },
};

#define MKTCSIZE (sizeof(MKTDecoder) / sizeof(MKTDecoder[0]))

#endif /*  __SGX_UKERNEL_STATUS_CODES_H__ */

/******************************************************************************
 End of file (sgx_ukernel_status_codes.h)
******************************************************************************/


